name: Check for debug statements

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check_debug_statements:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check for debug statements
        run: |
          # Define the patterns to search for
          PATTERNS=("dd(" "var_dump(" "error_log(")

          # Initialize a flag to track if any debug statements are found
          FOUND_DEBUG=0

          # Loop through each pattern
          for PATTERN in "${PATTERNS[@]}"
          do
            # Use grep to search for the pattern, excluding specific directories
            RESULT=$(grep -r -n -F "$PATTERN" --include=\*.php --exclude-dir=vendor --exclude-dir=resources --exclude-dir=public . || true)

            if [ ! -z "$RESULT" ]; then
              echo "Found $PATTERN:"
              echo "$RESULT"
              FOUND_DEBUG=1
            fi
          done

          # Check the flag and exit with an error if debug statements were found
          if [ $FOUND_DEBUG -eq 1 ]; then
            echo "Error: Debug statements found. Please remove them before merging."
            exit 1
          else
            echo "No debug statements found."
          fi
